// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5O6NInBoDDcDEo9Enb1DimnKz6Hu8ckQ',
    appId: '1:301750432881:android:c368a84ae2f864479897d0',
    messagingSenderId: '301750432881',
    projectId: 'ai-shopping-appginiusx',
    storageBucket: 'ai-shopping-appginiusx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSF2Y9W2IB3Q95HkM4YDViBZmJD5kg6lk',
    appId: '1:301750432881:ios:71c2e79095f4cff39897d0',
    messagingSenderId: '301750432881',
    projectId: 'ai-shopping-appginiusx',
    storageBucket: 'ai-shopping-appginiusx.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSF2Y9W2IB3Q95HkM4YDViBZmJD5kg6lk',
    appId: '1:301750432881:ios:af881a2bbd6252cd9897d0',
    messagingSenderId: '301750432881',
    projectId: 'ai-shopping-appginiusx',
    storageBucket: 'ai-shopping-appginiusx.appspot.com',
    iosBundleId: 'com.example.shoppingApp.RunnerTests',
  );
}
